spring.application.name=Financial-and-Accounting-Team-MS

server.port=7077

# Eureka Client Configuration
spring.cloud.discovery.enabled=true

spring.data.mongodb.uri=mongodb://localhost:27017/MEPMS_DB

spring.main.allow-circular-references=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Validation Logging
logging.level.org.springframework.web=DEBUG

# General Logging
logging.level.root=INFO

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akashvadnal699@gmail.com
spring.mail.password=furl ekme rlgm qugv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

